#!/bin/bash

THIS_DIR=$(dirname "${BASH_SOURCE[0]}")
ROOT_DIR="$THIS_DIR/.."
PHP_CS_FIXER="$ROOT_DIR/bin/php-cs-fixer"

FILES=${1:-$(pwd)}


if [ -z "$PHP_CS_FIX_CONFIG" ]; then
  if test -f "$ROOT_DIR/config/risky.php"; then
      PHP_CS_FIX_CONFIG="$ROOT_DIR/config/risky.php"
  elif test -f "$ROOT_DIR/vendor/christianjbrown/php-code-quality-scripts/config/risky.php"; then
      PHP_CS_FIX_CONFIG="$ROOT_DIR/vendor/christianjbrown/php-code-quality-scripts/config/risky.php"
  else
      echo "No PHP CS Fixer rules file set, and defaults not found in normal location." 1>&2
      exit 1
  fi
elif ! test -f "$PHP_CS_FIX_CONFIG"; then
  echo "PHP CS Fixer rules file $PHP_CS_FIX_CONFIG not found." 1>&2
  exit 1
fi

echo "Running php-cs-fixer on $FILES with rules file $PHP_CS_FIX_CONFIG ..."
$PHP_CS_FIXER fix "$FILES" -vvv --config="$PHP_CS_FIX_CONFIG"
