#!/bin/bash

THIS_DIR=$(dirname "${BASH_SOURCE[0]}")
ROOT_DIR="$THIS_DIR/.."

if [ -z "$PHP_CS" ]; then
  if test -f "$ROOT_DIR/bin/phpcs"; then
      PHP_CS="$ROOT_DIR/bin/phpcs"
  elif test -f "$THIS_DIR/phpcs"; then
      PHP_CS="$THIS_DIR/phpcs"
  else
      echo "No PHP CodeSniffer executable set, and defaults not found in normal location." 1>&2
      exit 1
  fi
elif ! test -f "$PHP_CS"; then
  echo "PHP CodeSniffer executable $PHP_CS not found." 1>&2
  exit 1
fi

SINCE_COMMIT=${1:-HEAD}

if [ -z "$PHP_CS_STANDARD" ]; then
  if test -f "$ROOT_DIR/config/standard.xml"; then
      PHP_CS_STANDARD="$ROOT_DIR/config/standard.xml"
  elif test -f "$ROOT_DIR/vendor/christianjbrown/php-code-quality-scripts/config/standard.xml"; then
      PHP_CS_STANDARD="$ROOT_DIR/vendor/christianjbrown/php-code-quality-scripts/config/standard.xml"
  else
      echo "No PHP CodeSniffer standard set, and defaults not found in normal location." 1>&2
      exit 1
  fi
elif ! test -f "$PHP_CS_STANDARD"; then
  echo "PHP CodeSniffer standard $PHP_CS_STANDARD not found." 1>&2
  exit 1
fi

function check() {
	if [[ $1 == *\.php ]]; then
		if php -l "$1" > /dev/null; then
		  echo "Checking $1"
			$PHP_CS --standard="$PHP_CS_STANDARD" "$1"
		else
			echo "\033[0;31mLinting fail in $1\033[0m"
			exit 1
		fi
	fi
}

pushd "$(git rev-parse --show-toplevel)" > /dev/null|| exit

# New and changed files
for file in $(git diff --name-only --diff-filter=MRACX "$SINCE_COMMIT"); do
  check "$file";
done

# Untracked files
for file in $(git ls-files --others --exclude-standard); do
  check "$file";
done

popd > /dev/null || exit
