#!/bin/bash

THIS_DIR=$(dirname "${BASH_SOURCE[0]}")
ROOT_DIR="$THIS_DIR/.."
PHP_CS_FIXER="$THIS_DIR/php-cs-fixer"

FILES=${1:-$(pwd)}
if [ -z "$PHP_CS_FIX_CONFIG" ]; then
  PHP_CS_FIX_CONFIG=$ROOT_DIR/rule-sets/risky.php
fi

echo "Running php-cs-fixer on $FILES with config from $PHP_CS_FIX_CONFIG ..."
$PHP_CS_FIXER fix "$FILES" -vvv --config="$PHP_CS_FIX_CONFIG"
