#!/bin/bash

THIS_DIR=$(dirname "${BASH_SOURCE[0]}")
ROOT_DIR="$THIS_DIR/.."
PHP_CS_FIXER="$ROOT_DIR/bin/php-cs-fixer"

SINCE_COMMIT=${1:-HEAD}

if [ -z "$PHP_CS_FIX_CONFIG_RISKY" ]; then
  if test -f "$ROOT_DIR/config/risky.php"; then
      PHP_CS_FIX_CONFIG_RISKY="$ROOT_DIR/config/risky.php"
  elif test -f "$ROOT_DIR/vendor/christianjbrown/php-code-quality-scripts/config/risky.php"; then
      PHP_CS_FIX_CONFIG_RISKY="$ROOT_DIR/vendor/christianjbrown/php-code-quality-scripts/config/risky.php"
  else
      echo "No PHP CS Fixer risky rules file set, and defaults not found in normal location." 1>&2
      exit 1
  fi
elif ! test -f "$PHP_CS_FIX_CONFIG_RISKY"; then
  echo "PHP CS Fixer risky rules file $PHP_CS_FIX_CONFIG_RISKY not found." 1>&2
  exit 1
fi

if [ -z "$PHP_CS_FIX_CONFIG_SAFE" ]; then
  if test -f "$ROOT_DIR/config/safe.php"; then
      PHP_CS_FIX_CONFIG_SAFE="$ROOT_DIR/config/safe.php"
  elif test -f "$ROOT_DIR/vendor/christianjbrown/php-code-quality-scripts/config/safe.php"; then
      PHP_CS_FIX_CONFIG_SAFE="$ROOT_DIR/vendor/christianjbrown/php-code-quality-scripts/config/safe.php"
  else
      echo "No PHP CS Fixer SAFE rules file set, and defaults not found in normal location." 1>&2
      exit 1
  fi
elif ! test -f "$PHP_CS_FIX_CONFIG_SAFE"; then
  echo "PHP CS Fixer SAFE rules file $PHP_CS_FIX_CONFIG_SAFE not found." 1>&2
  exit 1
fi

function fix() {
	if [[ $1 == *\.php ]]; then
		if php -l "$1" > /dev/null; then
		  echo "Fixing $1"
			$PHP_CS_FIXER fix "$1" --config="$2"
		else
			echo "\033[0;31mLinting fail in $1\033[0m"
			exit 1
		fi
	fi
}

pushd "$(git rev-parse --show-toplevel)" > /dev/null|| exit

# Existing files
for file in $(git diff --name-only --diff-filter=MR "$SINCE_COMMIT"); do
  fix "$file" "$PHP_CS_FIX_CONFIG_SAFE";
done

# New files (can be riskier rules)
for file in $(git diff --name-only --diff-filter=ACX "$SINCE_COMMIT"); do
	fix "$file" "$PHP_CS_FIX_CONFIG_RISKY";
done

# Untracked files (can be riskier rules)
for file in $(git ls-files --others --exclude-standard); do
  fix "$file" "$PHP_CS_FIX_CONFIG_RISKY";
done

popd > /dev/null || exit
