#!/bin/bash

THIS_DIR=$(dirname "${BASH_SOURCE[0]}")
ROOT_DIR="$THIS_DIR/.."
PHP_CS="$ROOT_DIR/bin/phpcs"

FILES=${1:-$(pwd)}
if [ -z "$PHP_CS_STANDARD" ]; then
  PHP_CS_STANDARD="$ROOT_DIR/standards/ChristianBrown/ruleset.xml"
fi

echo "Running phpcs on $FILES with standard from $PHP_CS_STANDARD ..."
$PHP_CS --standard="$PHP_CS_STANDARD" "$FILES"
