#!/bin/bash

THIS_DIR=$(dirname "${BASH_SOURCE[0]}")
ROOT_DIR="$THIS_DIR/.."
PHP_CS_FIXER="$ROOT_DIR/bin/php-cs-fixer"

SINCE_COMMIT=${1:-HEAD}

if [ -z "$PHP_CS_FIX_CONFIG_RISKY" ]; then
  PHP_CS_FIX_CONFIG_RISKY=$ROOT_DIR/rule-sets/risky.php
fi
if [ -z "$PHP_CS_FIX_CONFIG_SAFE" ]; then
  # For now, we use the same config for safe and risky, see README.md
  PHP_CS_FIX_CONFIG_SAFE=$PHP_CS_FIX_CONFIG_RISKY
fi


function fix() {
	if [[ $1 == *\.php ]]; then
		if php -l "$1" > /dev/null; then
		  echo "Fixing $1"
			$PHP_CS_FIXER fix "$1" --config="$2"
		else
			echo "\033[0;31mLinting fail in $1\033[0m"
			exit 1
		fi
	fi
}

pushd "$(git rev-parse --show-toplevel)" > /dev/null|| exit

# Existing files
for file in $(git diff --name-only --diff-filter=MR "$SINCE_COMMIT"); do
  fix "$file" "$PHP_CS_FIX_CONFIG_SAFE";
done

# New files (can be riskier rules)
for file in $(git diff --name-only --diff-filter=ACX "$SINCE_COMMIT"); do
	fix "$file" "$PHP_CS_FIX_CONFIG_RISKY";
done

# Untracked files (can be riskier rules)
for file in $(git ls-files --others --exclude-standard); do
  fix "$file" "$PHP_CS_FIX_CONFIG_RISKY";
done

popd > /dev/null || exit
