#!/bin/bash

THIS_DIR=$(dirname "${BASH_SOURCE[0]}")
ROOT_DIR="$THIS_DIR/.."

echo THIS_DIR
exit 1

if [ -z "$PHP_CS" ]; then
  if test -f "$ROOT_DIR/bin/phpcs"; then
      PHP_CS="$ROOT_DIR/bin/phpcs"
  elif test -f "$THIS_DIR/phpcs"; then
      PHP_CS="$THIS_DIR/phpcs"
  else
      echo "No PHP CodeSniffer executable set, and defaults not found in normal location." 1>&2
      exit 1
  fi
elif ! test -f "$PHP_CS"; then
  echo "PHP CodeSniffer executable $PHP_CS not found." 1>&2
  exit 1
fi

FILES=${1:-$(pwd)}
if [ -z "$PHP_CS_STANDARD" ]; then
  if test -f "$ROOT_DIR/config/standard.xml"; then
      PHP_CS_STANDARD="$ROOT_DIR/config/standard.xml"
  elif test -f "$ROOT_DIR/vendor/christianjbrown/php-code-quality-scripts/config/standard.xml"; then
      PHP_CS_STANDARD="$ROOT_DIR/vendor/christianjbrown/php-code-quality-scripts/config/standard.xml"
  else
      echo "No PHP CodeSniffer standard set, and defaults not found in normal location." 1>&2
      exit 1
  fi
elif ! test -f "$PHP_CS_STANDARD"; then
  echo "PHP CodeSniffer standard $PHP_CS_STANDARD not found." 1>&2
  exit 1
fi

echo "Running phpcs on $FILES with standard from $PHP_CS_STANDARD ..."
$PHP_CS --standard="$PHP_CS_STANDARD" "$FILES"
